image: ghcr.io/acsone/deploy-tools

test:
  tags:
    - generic
  script:
    - echo "running tests of ${CI_COMMIT_REF_NAME}"
    - kubectl config get-contexts
    - mkdir -p tocache
    - ls -al tocache
    - echo toto > tocache/titi
  cache:
    key: .gitlab-ci.yml
    path:
      - tocache