image: ubuntu:18.04

services:
  - postgres:11

test:
  tags:
  - odoo-ci-test
  script: 
    - echo $PGHOST
    - echo $PGUSER
    - python3 -m venv venv
    - venv/bin/pip install acsoo requests
    - exit 0
    - apt update
    - apt -y install software-properties-common
    - add-apt-repository -y ppa:projectatomic/ppa
    - apt -y install buildah libdevmapper-dev
    - mkdir /tmp/toto
    - cd /tmp/toto
    - echo "FROM docker.io/ubuntu:18.04" >> Dockerfile
    - echo "RUN echo toto > /tmp/toto" >> Dockerfile
    - buildah --storage-driver=vfs bud --isolation=chroot -t test .