variables:
  DB_NAME: "${CI_PROJECT_NAME}-${CI_PIPELINE_ID}"

before_script: |
    function sbihello {
        echo "hello"
    }

after_script:
  - "echo after_script: ${DB_NAME}"

test:
  tags:
    - python
  script:
    - sbihello
    - echo "failing"
    - exit 1
    - echo "after failing"
