image: python:3

test:
  script: 
    - pip install coverage
    - coverage run --branch sbi.py
    - coverage html
  artifacts:
    paths:
      - htmlcov
    expire_in: 2 days
  
pages:
  dependencies:
    - test
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 2 days
  only:
    - master
