image: ghcr.io/acsone/deploy-tools

test:
  script:
    - echo "running tests of ${CI_COMMIT_REF_NAME}"
    - kubectl config get-contexts

.deploy-trigger:
  script:
    - echo "triggering deploy of ${CI_COMMIT_REF_NAME} to ${CI_ENVIRONMENT_NAME}"
    - |
      curl --request POST \
        --form "token=$CI_JOB_TOKEN" \
        --form "ref=deploy" \
        --form "variables[DEPLOY_ENV]=${CI_ENVIRONMENT_NAME}" \
        --form "variables[DEPLOY_COMMIT_REF_NAME]=${CI_COMMIT_REF_NAME}" \
        "$CI_API_V4_URL/projects/$CI_PROJECT_ID/trigger/pipeline"

deploy-test-trigger:
  extends: .deploy-trigger
  environment:
    name: test
  only:
    - master
  when:
    manual

build-review-image:
  script:
    - echo build review image
  when: manual

deploy-review-trigger:
  extends: .deploy-trigger
  environment:
    name: review/${CI_COMMIT_REF_NAME}
    on_stop: stop-review-trigger
  except:
    - master
  needs:
    - build-review-image

stop-review-trigger:
  script:
    - echo stopping undeployed environment ${CI_ENVIRONMENT_NAME}
  environment:
    name: review/${CI_COMMIT_REF_NAME}
    action: stop
  except:
    - master
  when:
    manual
