before_script:
  - MYVAR=myvar
  - echo "before_script myvar = ${MYVAR}"

after_script:
  - echo "after_script myvar = ${MYVAR}"

test:
  script:
    - echo ${PGHOST}
    - echo ${PGUSER}
    - createdb mydb
    - psql -d mydb -c "select * from pg_catalog.pg_tables"
    - pip install psycopg2 -f https://wheelhouse.acsone.eu/manylinux1
    - python test.py
