.deploy-trigger:
  script:
    - echo "triggering deploy of ${CI_ENVIRONMENT_SLUG}

.stop-trigger:
  script:
    - echo "triggering stop of ${CI_ENVIRONMENT_SLUG}

deploy-test-trigger:
  extends: .deploy-trigger
  variables:
    DEPLOY_ENV: theenv
    DEPLOY_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME
  environment:
    name: test
    on_stop: stop-test-trigger
  when:
    manual

stop-test-trigger:
  extends: .stop-trigger
  variables:
    DEPLOY_ENV: theenv
    DEPLOY_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME
  environment:
    name: test
    action: stop
  when:
    manual

deploy-review-trigger:
  extends: .deploy-trigger
  variables:
    DEPLOY_ENV: review
    DEPLOY_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME
  environment:
    name: review/${DEPLOY_COMMIT_REF_NAME}
    on_stop: stop-review-trigger
  when:
    manual

stop-review-trigger:
  extends: .stop-trigger
  variables:
    DEPLOY_ENV: review
    DEPLOY_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME
  environment:
    name: review/${DEPLOY_COMMIT_REF_NAME}
    action: stop
  when:
    manual
