image: ghcr.io/acsone/deploy-tools

test:
  script:
    - echo "running tests of ${CI_COMMIT_REF_NAME}"
    - exit 0

.deploy-trigger:
  script:
    - echo "triggering deploy of ${CI_COMMIT_REF_NAME} to ${CI_ENVIRONMENT_NAME} (stop=${DEPLOY_STOP})"
    - |
      curl --request POST \
        --form "token=$CI_JOB_TOKEN" \
        --form "ref=deploy" \
        --form "variables[DEPLOY_ENV]=${CI_ENVIRONMENT_NAME}" \
        --form "variables[DEPLOY_COMMIT_REF_NAME]=${CI_COMMIT_REF_NAME}" \
        --form "variables[DEPLOY_STOP]=${DEPLOY_STOP}" \
        "$CI_API_V4_URL/projects/$CI_PROJECT_ID/trigger/pipeline"

deploy-test-trigger:
  extends: .deploy-trigger
  environment:
    name: test
  only:
    - master
  when:
    manual

deploy-review-trigger:
  extends: .deploy-trigger
  environment:
    name: review/${CI_COMMIT_REF_NAME}
    on_stop: stop-review-trigger
  except:
    - master
  when:
    manual

stop-review-trigger:
  extends: .deploy-trigger
  variables:
    DEPLOY_STOP: "true"
  environment:
    name: review/${CI_COMMIT_REF_NAME}
    action: stop
  except:
    - master
  when:
    manual
