variables:
  DB_NAME: "${CI_PROJECT_NAME}-${CI_PIPELINE_ID}"

after_script:
  - "echo after_script: ${DB_NAME}"

test:
  tags:
    - python
  script:
    - echo "failing"
    - exit 1
    - echo "after failing"