before_script:
  - MYVAR=myvar
  - echo "myvar = ${MYVAR}"

after_script:
  - echo "myvar = ${MYVAR}"

myfailingjob:
  script:
    - echo "myvar = ${MYVAR}"
    - exit 1

mysucceedingjob:
  script:
    - echo "myvar = ${MYVAR}"
