stages:
  - test

.deploy-trigger:
  trigger:
    project: sbidoul/sandbox
    branch: deploy

test:
  extends: .deploy-trigger
  stage: test
  variables:
    DEPLOY_ENV: theenv
    DEPLOY_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME
  when:
    manual

review:
  extends: .deploy-trigger
  stage: test
  variables:
    DEPLOY_ENV: review
    DEPLOY_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME
  when:
    manual
