stages:
  - test

test:
  stage: test
  variables:
    DEPLOY_ENV: theenv
  trigger:
    include:
      - project: $CI_PROJECT_PATH
        ref: deploy
        file: .gitlab-ci.yml
  when:
    manual
