before_script:
  - MYVAR=myvar
  - echo "before_script myvar = ${MYVAR}"

after_script:
  - echo "after_script myvar = ${MYVAR}"

test:
  script:
    - createdb mydb
    - echo ${PGHOST}
    - echo ${PGUSER}
    - psql -d mydb -c "select * from pg_catalog.pg_tables"
