image: python:3

stages:
  - test
  - deploy

test:
  stage: test
  script: 
    - pip install coverage
    - coverage run --branch sbi.py
    - coverage html
  artifacts:
    paths:
      - htmlcov
    expire_in: 2 days
