before_script:
  - MYVAR=myvar
  - echo "before_script: myvar = ${MYVAR}"

after_script:
  - echo "after_script: myvar = ${MYVAR}"

myfailingjob:
  script:
    - echo "myfailingjob: myvar = ${MYVAR}"
    - exit 1

mysucceedingjob:
  script:
    - echo "mysucceedingjob: myvar = ${MYVAR}"
