[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "sbitest"
author = "ACSONE SA/NV"
author-email = "info@acsone.eu"
classifiers = ["License :: OSI Approved :: MIT License"]

