name: test-python

on: [push, pull_request]

jobs:
  test-python:
    runs-on: ubuntu-latest
    name: Test Python
    steps:
      - run: |
          python3 -m venv venv
          venv/bin/python --version
